export const GET_USER_REQUEST = 'CREATE_USER_REQUEST';
export const GET_USER_FAILURE = 'CREATE_USER_FAILURE';
export const GET_USER_SUCCESS = 'CREATE_USER_SUCCESS';

export const GET_USER_HISTORY = 'CREATE_USER_HISTORY';